const LOAD_RESOURCES = {
	"story/SingularityCore.gd": {"load_type": "script", "onready": false},
	"story/Vilcy.gd": {"load_type": "script", "onready": false},
	"story/HugeRock.gd": {"load_type": "script", "onready": false},
	"story/LifepodIsFloating.gd": {"load_type": "script", "onready": false},
	"story/PirateCombat.gd": {"load_type": "script", "onready": false},
	"story/PirateTrap.gd": {"load_type": "script", "onready": false},
	"story/RescueOperation.gd": {"load_type": "script", "onready": false},
	"story/HybridHunter.gd": {"load_type": "script", "onready": false},
	"story/ClaimBeaconForeign.gd": {"load_type": "script", "onready": false},
	"story/Singularity.gd": {"load_type": "script", "onready": false},
	"story/InterCrewBanter.gd": {"load_type": "script", "onready": false},
	"story/LocustSwarm.gd": {"load_type": "script", "onready": false},
	"story/AimingAsteroid.gd": {"load_type": "script", "onready": false},
	"story/AimingAsteroidShower.gd": {"load_type": "script", "onready": false},
	"story/HumongousHollowRock.gd": {"load_type": "script", "onready": false},
	"story/InstanceWithChance.gd": {"load_type": "script", "onready": false},
	"story/Minefield.gd": {"load_type": "script", "onready": false},
	"story/TimedEvent.gd": {"load_type": "script", "onready": false},
	"ships/ship-ctrl.gd": {"load_type": "script", "onready": false},
	"enceladus/SystemShipUpgradeUI.gd": {"load_type": "script", "onready": false},
	"CurrentGame.gd": {"load_type": "script", "onready": false},
	"TheRing.gd": {"load_type": "script", "onready": false},
	"Game.gd": {"load_type": "script", "onready": false},
}
